[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
future_takeover_program = "6p1zdbGeiNQmegXSNhkqSRrumFVf2GgbaVX3M5LMpgV5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
