[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
future_takeover_program = "5fgVyP9E5cWqvj2z5421932uLzQuqPgEwA62TUWtaNDw"

[programs.devnet]
future_takeover_program = "5fgVyP9E5cWqvj2z5421932uLzQuqPgEwA62TUWtaNDw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
